name: CI Pipeline

on:
  push:
    branches: [server-only]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5


      - name: Trigger Coolify deploy
        env:
          COOLIFY_URL: ${{ secrets.COOLIFY_DOMAIN }}    # ex: http://89.41.182.64:8000 sau https://coolify.turliucezar.duckdns.org
          COOLIFY_UUID: ${{ secrets.COOLIFY_UUID }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          curl -sSf -X POST "$COOLIFY_URL/api/v1/deploy" \
            -H "Authorization: Bearer $COOLIFY_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"uuid\":\"$COOLIFY_UUID\",\"force\":true}"